Repository Robert-Fairley/apple-news-format, pull requests merged in 2019-12, with the labels that each got.

#26 Issue metadata
  package-lock.json
  package.json
  src/index.ts
  src/metadata/index.ts
  src/metadata/issue.ts
  src/metadata/metadata.ts
Labels: Housekeeping, enhancement

#27 [ Patch / Nonversioning ] Rm some int annotations
  src/article-layout/component-layout-base.ts
  src/primitives/margin.ts
Labels: Housekeeping

#28 [ Patch ] Add missing optional value types
  src/styles/text-styles/component-text-style-base.ts
  src/styles/text-styles/text-style-base.ts
Labels: Housekeeping, bug

#29 Fix Video component type
  src/apple-news.d.ts
  src/index.ts
Labels: bug
