Repository Robert-Fairley/apple-news-format, pull requests merged in 2019-11, with the labels that each got.

#18 ComponentLayout & ComponentStyle property fixes
  src/article-layout/component-layout-base.ts
  src/styles/component-styles/component-style-base.ts
Labels: Housekeeping, bug

#19 Component layout/1.10.1
  .circleci/config.yml
  src/article-layout/component-layout-base.ts
Labels: Housekeeping, bug, enhancement

#20 Fix hyphenation field typo
  src/styles/text-styles/component-text-style-base.ts
Labels: Housekeeping, bug

#21 Add missing fields to CollectionDisplay
  src/components/article-structure/collection-display.ts
Labels: bug, enhancement

#22 Fix optional property on CollectionDisplay
  src/components/article-structure/collection-display.ts
Labels: Housekeeping, bug

#24 Build on prepublishOnly & only publish lib
  package.json
Labels: Housekeeping, enhancement
